name: uber_demo_app
description: A Flutter demo application that mimics core Uber functionality with a clean, modern UI.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Maps & Location (Free OpenStreetMap instead of Google Maps)
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  location: ^5.0.3
  geocoding: ^2.1.1
  geolocator: ^10.1.0

  # State Management
  provider: ^6.1.1

  # HTTP & Networking
  http: ^1.1.2

  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.2.2

  # UI Components
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/maps/

  # fonts:
    # - family: Uber
    #   fonts:
    #     - asset: assets/fonts/UberMove-Regular.ttf
    #     - asset: assets/fonts/UberMove-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/UberMove-Bold.ttf
    #       weight: 700 